### ISSUE TITLE
thread dumps in the logs

### ISSUE THREAD

**Issue by mrcoffee1026** [SpaicyGaming/AntiCommandSuggestions#1]
they begin with

```
[21:45:43] [Server thread/WARN]: java.lang.ClassCastException: me.libraryaddict.disguise.disguisetypes.watchers.SnowmanWatcher cannot be cast to com.comphenix.protocol.wrappers.WrappedChatComponent
[21:45:43] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.json.SerializerChatComponent.serialize(SerializerChatComponent.java:11)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.Gson.toJson(Gson.java:669)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.Gson.toJsonTree(Gson.java:562)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:158)
[21:45:43] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.json.SerializerDisguise.serialize(SerializerDisguise.java:60)
[21:45:43] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.json.SerializerDisguise.serialize(SerializerDisguise.java:13)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:93)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.Gson.toJson(Gson.java:669)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.Gson.toJson(Gson.java:648)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.Gson.toJson(Gson.java:603)
[21:45:43] [Server thread/WARN]: 	at com.google.gson.Gson.toJson(Gson.java:583)
[21:45:43] [Server thread/WARN]: 	at me.libraryaddict.disguise.utilities.DisguiseUtilities.saveDisguises(DisguiseUtilities.java:223)
[21:45:43] [Server thread/WARN]: 	at me.libraryaddict.disguise.DisguiseListener.onChunkUnload(DisguiseListener.java:267)
[21:45:43] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor244.execute(Unknown Source)
[21:45:43] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:45:43] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:45:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[21:45:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:441)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:403)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:282)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1091)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[21:45:43] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[21:45:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```

And go on to infinity from the point where the server starts.  I'm not sure what disguises and snowmen have to do with anything but "libraryaddict" caught my eye as being the dev of this plugin.  If you have some scheduled routine in this plugin that loads and unloads chunks... and I have no idea why you would need that for this plugin to work, but it is going to need another approach if this is the result.

**Comment by mrcoffee1026** [comment]
never mind this it was libsdisguises i should have known better.  I tried the latest jenkins and the issue went away thanks.
